### ISSUE TITLE
node throws few erros

### ISSUE THREAD

**Issue by olegmeglin** [bubkoo/ascii-progress#3]
First I got this error:

```
.../node_modules/ascii-progress/index.js:468
return new Array(count + 1).join(char);
RangeError: Invalid array length
```

I fixed that error by replacing this...

``` javascript
return new Array(count + 1).join(char);
```

.. with this ...

``` javascript
return [(count + 1)].join(char);
```

Now I get the next error:

```
.../node_modules/ascii-progress/index.js:439
this.cursor.moveTo(this.savePos.row, this.savePos.col);
TypeError: Cannot read property 'row' of undefined
```

Any idea how to fix it?
I'm running node v4.4.7 on OSX 10.11.5

**Comment by bubkoo** [comment]
@meglinmedia Is any example in `/examples` can good running?

**Comment by olegmeglin** [comment]
Now I know what's wrong. The errors I described be thrown only in my development environment (PHPStorm 2016.2) while using the Run/Debug Console.

By using the Terminal, everything's works like a charm.
