### ISSUE TITLE
code `options.clean`, readme `options.clear` mismatch

### ISSUE THREAD

**Issue by magicdawn** [bubkoo/ascii-progress#30]
readme use `options.clear` to dispose the progress bar after complete
the code use `options.clean` to do the same thing 

Is there a mistake or just I'm get wrong?

https://github.com/bubkoo/ascii-progress/blob/9b0cc91cad6e4c553ac285d49a95e02322ded4c8/index.js#L108

![image](https://user-images.githubusercontent.com/4067115/59242693-197d9680-8c3f-11e9-9cb6-ae062254171d.png)

**Comment by bubkoo** [comment]
@magicdawn Readme updated, https://github.com/bubkoo/ascii-progress#options
